### Задача 1. Использование строк

Необходимо определить, является ли введённая строка палиндромом. Вывести yes, если является, и no в противном случае.

**Sample Input:**

abcdabcd

**Sample Output:**

no

In [1]:
s = input()
l = len(s)
res = ""
for i in range(l-1,-1,-1):
    res += s[i]
if res == s:
    print("yes")
else:
    print("no")

abcdabcd
no


### Задача 2. Использование списков и массивов

Программа принимает на вход четыре натуральных числа N, M, K, S, разделённых пробелом. Необходимо создать целочисленный двумерный массив numpy, содержащий N строк и M столбцов и заполнить его единицами. Затем умножить все чётные строки (0, 2, 4, ...) на K, а все нечётные столбцы (1, 3, 5, ...) умножить на S. Программа должна вывести на экран сумму всех элементов полученного массива.

**Sample Input:**

2 3 2 5

**Sample Output:**

21

In [3]:
import numpy as np

N, M, K, S = map(int, input().split(" "))
res = 0
mas = np.ones((N, M))
for i in range(0, N):
    for j in range(0, M):
        if i % 2 == 0:
            mas[i][j] = mas[i][j] * K
        if j % 2 != 0:
            mas[i][j] = mas[i][j] * S
        res += mas[i][j]
print(int(res))

2 3 2 5
21


### Задание 3. Формирование массива циклами и условиями/библиотеками numpy

Необходимо сформировать случайный целочисленный массив numpy размером N строк на M столбцов. N и M задать с клавиатуры. Далее нужно вычислить минимальный элемент в каждом стоблце. 

Реализовать двумя способами:  
a) Без использования вспомогательных функций, используя только циклы и условия;  
b) С использованием специальной функции из библиотеки numpy.

Вывести полученные минимальные элементы в следующем формате (для каждого столбца своё предложение):

*Минимальный элемент в 1 столбце равен m1*  
*Минимальный элемент в 2 столбце равен m2*  
*...*  
*Минимальный элемент в M столбце равен mM*  

In [6]:
#а) без использования вспомогательных функций, используя циклы и условия
from random import randint
import numpy as np
N, M = map(int, input("Введите число строк и столбцов массива через пробел: ").split())
a = [[randint(-100,100) for j in range(M)] for i in range(N)] 
print(a)
massiv = np.array(a)
n = 0
min_n = 101
for c in massiv.T:
    min_n = 101
    for m in c:
        if m < min_n:
            min_n = m
    n += 1
    print(f"Минимальный элемент в {n} столбце равен {min_n}")

Введите число строк и столбцов массива через пробел: 3 3
[[-57, -98, 20], [14, 3, 95], [72, -69, 82]]
Минимальный элемент в 1 столбце равен -57
Минимальный элемент в 2 столбце равен -98
Минимальный элемент в 3 столбце равен 20


In [7]:
#b) с использованием специальной функции из библиотеки numpy
from random import randint
import numpy as np
N, M = map(int, input("Введите число строк и столбцов массива через пробел: ").split())
massiv = np.random.randint(-100,100, (N, M))
print(massiv)
min_n = np.min(massiv, axis = 0)
for i in range(0,M):
    if i <= M:
        print(f"Минимальный элемент в {i + 1} столбце равен {min_n[i]}")
        i += 1

Введите число строк и столбцов массива через пробел: 6 3
[[ 80 -26  86]
 [ 44 -30  99]
 [-16 -30 -83]
 [-49  62  35]
 [-38 -14 -43]
 [ 22  10  35]]
Минимальный элемент в 1 столбце равен -49
Минимальный элемент в 2 столбце равен -30
Минимальный элемент в 3 столбце равен -83
